apiVersion: v1
kind: Secret
metadata:
  name: gitea-oci-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: gitea-oci
  url: oci://gitea.applications.svc.cluster.local:3000/remotelab
  enableOCI: "true"
  username: remotelab
  password: remotelab
  insecure: "true"
