apiVersion: v1
kind: Secret
metadata:
  name: gitea-registry-secret
  namespace: applications
  labels:
    app: gitea-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {"auths":{"gitea:3000":{"username":"remotelab","password":"remotelab","auth":"cmVtb3RlbGFiOnJlbW90ZWxhYg=="}}}
