apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "django-app.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "django-app.selectorLabels" . | nindent 4 }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  type: {{ .Values.service.type }}
