apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: applications

resources:
  - ../../base

# ArgoCD Image Updater will automatically add:
# images:
# - name: ghcr.io/lpmi-13/k3s-remotelab-django
#   newName: gitea:3000/remotelab/django-app
#   newTag: 1.0.X
